### ISSUE TITLE
Importing Gilroy Font from public is giving a 404

### ISSUE THREAD

**Issue by alvarosabu** [Dawntraoz/slidev-theme-unicorn#1]
# Steps to reproduce

1. Install theme
2. Add theme to slides

# Error
<img width="1482" alt="Screenshot 2021-06-10 at 12 38 36" src="https://user-images.githubusercontent.com/4699008/121511346-d058ac80-c9e8-11eb-847b-45f6bdc566a2.png">

`Failed to load resource: the server responded with a status of 404 (Not Found)`

I'm having the same issue with all the assets in public

**Comment by IanVS** [comment]
FWIW, I created a `/public/fonts` directory in my project and copied the font file there, and it works correctly now.

**Comment by Dawntraoz** [comment]
Thanks for reporting it guys, this has been fixed in the version 1.1.0 at #2 💜
